-- CONFLICTREPORT_SANDBOX.PUBLIC.PAYER_DASHBOARD_CON_TYP_NEW_CALC_V2 definition

create or replace TABLE CONFLICTREPORT_SANDBOX.PUBLIC.PAYER_DASHBOARD_CON_TYP_NEW_CALC_V2 cluster by (
    PAYERID, CRDATEUNIQUE, CONTYPE, STATUSFLAG, COSTTYPE, VISITTYPE
)(
	PAYERID VARCHAR(50),
	CRDATEUNIQUE DATE,
	CONTYPE VARCHAR(25),
	CONTYPEDESC VARCHAR(100),
	STATUSFLAG VARCHAR(5),
	COSTTYPE VARCHAR(20),
	VISITTYPE VARCHAR(20),
	CO_TO NUMBER(38,0),
	CO_SP NUMBER(38,2),
	CO_OP NUMBER(38,2),
	CO_FP NUMBER(38,2)
);