-- CONFLICTREPORT_SANDBOX.PUBLIC.STATE_DASHBOARD_AGENCY definition

create or replace TABLE CONFLICTREPORT_SANDBOX.PUBLIC.STATE_DASHBOARD_AGENCY cluster by (PAYERID,PROVIDERID, VISITDATE,  STATUSFLAG, COSTTYPE, VISITTYPE,COUNTY, SERVICECODE)(
	PAYERID VARCHAR(50),
	PROVIDERID VARCHAR(50),
	VISITDATE DATE,
	P_NAME VARCHAR(100),
	STATUSFLAG VARCHAR(5),
	COSTTYPE VARCHAR(20),
	VISITTYPE VARCHAR(20),
	COUNTY VARCHAR(100),
	SERVICECODE VARCHAR(50),
	CON_TO NUMBER(38,0),
	CON_SP NUMBER(38,2),
	CON_OP NUMBER(38,2),
	CON_FP NUMBER(38,2)
);


-- CONFLICTREPORT_SANDBOX.PUBLIC.STATE_DASHBOARD_CAREGIVER definition

create or replace TABLE CONFLICTREPORT_SANDBOX.PUBLIC.STATE_DASHBOARD_CAREGIVER cluster by (PAYERID,PROVIDERID, VISITDATE,SSN,C_NAME,STATUSFLAG,COSTTYPE,VISITTYPE,COUNTY,SERVICECODE)(
	PAYERID VARCHAR(50),
	PROVIDERID VARCHAR(50),
	VISITDATE DATE,
	SSN VARCHAR(50),
	C_NAME VARCHAR(100),
	STATUSFLAG VARCHAR(5),
	COSTTYPE VARCHAR(20),
	VISITTYPE VARCHAR(20),
	COUNTY VARCHAR(100),
	SERVICECODE VARCHAR(50),
	CON_TO NUMBER(38,0),
	CON_SP NUMBER(38,2),
	CON_OP NUMBER(38,2),
	CON_FP NUMBER(38,2)
);


-- CONFLICTREPORT_SANDBOX.PUBLIC.STATE_DASHBOARD_CON_TYPE definition

create or replace TABLE CONFLICTREPORT_SANDBOX.PUBLIC.STATE_DASHBOARD_CON_TYPE cluster by (PAYERID, PROVIDERID, VISITDATE, CONTYPE, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY, SERVICECODE)(
	PAYERID VARCHAR(50),
	PROVIDERID VARCHAR(50),
	VISITDATE DATE,
	CONTYPE VARCHAR(50),
	CONTYPEDESC VARCHAR(100),
	STATUSFLAG VARCHAR(5),
	COSTTYPE VARCHAR(20),
	VISITTYPE VARCHAR(20),
	COUNTY VARCHAR(100),
	SERVICECODE VARCHAR(50),
	CON_TO NUMBER(38,0),
	CON_SP NUMBER(38,2),
	CON_OP NUMBER(38,2),
	CON_FP NUMBER(38,2)
);


-- CONFLICTREPORT_SANDBOX.PUBLIC.STATE_DASHBOARD_PATIENT definition

create or replace TABLE CONFLICTREPORT_SANDBOX.PUBLIC.STATE_DASHBOARD_PATIENT cluster by (PAYERID, PROVIDERID, VISITDATE, PATIENTID, PNAME, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY, SERVICECODE)(
	PAYERID VARCHAR(50),
	PROVIDERID VARCHAR(50),
	VISITDATE DATE,
	PATIENTID VARCHAR(50),
	PNAME VARCHAR(100),
	STATUSFLAG VARCHAR(5),
	COSTTYPE VARCHAR(20),
	VISITTYPE VARCHAR(20),
	COUNTY VARCHAR(100),
	SERVICECODE VARCHAR(50),
	CON_TO NUMBER(38,0),
	CON_SP NUMBER(38,2),
	CON_OP NUMBER(38,2),
	CON_FP NUMBER(38,2)
);


-- CONFLICTREPORT_SANDBOX.PUBLIC.STATE_DASHBOARD_PAYER definition

create or replace TABLE CONFLICTREPORT_SANDBOX.PUBLIC.STATE_DASHBOARD_PAYER cluster by (
PAYERID,PROVIDERID, VISITDATE, PNAME, STATUSFLAG, COSTTYPE, VISITTYPE,COUNTY,
	SERVICECODE
)(
	PAYERID VARCHAR(50),
	PROVIDERID VARCHAR(50),
	VISITDATE DATE,
	PNAME VARCHAR(100),
	STATUSFLAG VARCHAR(5),
	COSTTYPE VARCHAR(20),
	VISITTYPE VARCHAR(20),
	COUNTY VARCHAR(100),
	SERVICECODE VARCHAR(50),
	CON_TO NUMBER(38,0),
	CON_SP NUMBER(38,2),
	CON_OP NUMBER(38,2),
	CON_FP NUMBER(38,2)
);