-- CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_PAYER_01 definition

create or replace TABLE CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_PAYER_01 cluster by (
    PAYERID, PROVIDERID, OFFICEID, CRDATEUNIQUE, CONTYPES, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY
)(
	PAYERID VARCHAR(50),
	PROVIDERID VARCHAR(50),
	OFFICEID VARCHAR(50),
	CRDATEUNIQUE DATE,
	CONTYPE VARCHAR(50),
	CONTYPES VARCHAR(50),
	STATUSFLAG VARCHAR(5),
	COSTTYPE VARCHAR(20),
	VISITTYPE VARCHAR(20),
	COUNTY VARCHAR(100),
	CO_TO NUMBER(38,0),
	CO_SP NUMBER(38,2),
	CO_OP NUMBER(38,2),
	CO_FP NUMBER(38,2)
);