-- CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_PROVIDER_02 definition
USE ROLE READWRITE_CONFLICTREPORT_SANDBOX;
create or replace TABLE CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_PROVIDER_02 cluster by (
	PAYERSTATE, PAYERID, PROVIDERID, CRDATEUNIQUE, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY
)(
	PAYERSTATE VARCHAR(100),
	PAYERID VARCHAR(50),
	PROVIDERID VARCHAR(50),
	CRDATEUNIQUE DATE,
	STATUSFLAG VARCHAR(5),
	COSTTYPE VARCHAR(20),
	VISITTYPE VARCHAR(20),
	COUNTY VARCHAR(100),
	SERVICECODE VARCHAR(50),
	TO_TO NUMBER(38,0),
	TO_SP NUMBER(38,2),
	TO_OP NUMBER(38,2),
	TO_FP NUMBER(38,2),
	TD_TO NUMBER(38,0),
	TD_SP NUMBER(38,2),
	TD_OP NUMBER(38,2),
	TD_FP NUMBER(38,2),
	IN_TO NUMBER(38,0),
	IN_SP NUMBER(38,2),
	IN_OP NUMBER(38,2),
	IN_FP NUMBER(38,2)
);