-- Load aggregated payer dashboard data using reusable views

-- Clear existing data
TRUNCATE TABLE CONFLICTREPORT_SANDBOX.PUBLIC.PAYER_DASHBOARD_CON_TYP_NEW_CALC_V2;

-- Insert aggregated data for all active/non-demo payers via view
INSERT INTO CONFLICTREPORT_SANDBOX.PUBLIC.PAYER_DASHBOARD_CON_TYP_NEW_CALC_V2 (
    PAYERID, CRDATEUNIQUE, CONTYPE, CONTYPEDESC, STATUSFLAG, COSTTYPE, VISITTYPE,
    CO_TO, CO_SP, CO_OP, CO_FP
)
SELECT 
    PAYERID,
    CRDATEUNIQUE,
    CONTYPE,
    CONTYPEDESC,
    STATUSFLAG,
    COSTTYPE,
    VISITTYPE,
    CO_TO,
    CO_SP,
    CO_OP,
    CO_FP
FROM CONFLICTREPORT_SANDBOX.PUBLIC.VIEW_PAYER_CONFLICT_AGGREGATED;


