-- Load aggregated payer dashboard data using reusable views

-- Clear existing data
TRUNCATE TABLE CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_CON_TYPE_NEW_CALC;

-- Insert aggregated data for all active/non-demo payers via view
INSERT INTO CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_CON_TYPE_NEW_CALC (
    PAYERID, PROVIDERID, CRDATEUNIQUE, CONTYPE, CONTYPEDESC, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY, SERVICECODE,
    CO_TO, CO_SP, CO_OP, CO_FP
)
SELECT 
    PAYERID,
    PROVIDERID,
    CRDATEUNIQUE,
    CONTYPE,
    CONTYPEDESC,
    STATUSFLAG,
    COSTTYPE,
    VISITTYPE,
    COUNTY,
    SERVICECODE,
    CO_TO,
    CO_SP,
    CO_OP,
    CO_FP
FROM CONFLICTREPORT_SANDBOX.PUBLIC.VIEW_STATE_CONFLICT_AGGREGATED;


