-- CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_CON_TYPE_NEW_CALC definition

create or replace TABLE CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_CON_TYPE_NEW_CALC cluster by (
	PAYERID, PROVIDERID, CRDATEUNIQUE, CONTYPE, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY, SERVICECODE
)(
	PAYERID VARCHAR(50),
	PROVIDERID VARCHAR(50),
	CRDATEUNIQUE DATE,
	CONTYPE VARCHAR(25),
	CONTYPEDESC VARCHAR(100),
	STATUSFLAG VARCHAR(5),
	COSTTYPE VARCHAR(20),
	VISITTYPE VARCHAR(20),
	COUNTY VARCHAR(100),
	SERVICECODE VARCHAR(50),
	CO_TO NUMBER(38,0),
	CO_SP NUMBER(38,2),
	CO_OP NUMBER(38,2),
	CO_FP NUMBER(38,2)
);