TEST_STATE_AGENCY_NEW_CALC
TEST_STATE_CAREGIVER_NEW_CALC
TEST_STATE_PATIENT_NEW_CALC
TEST_STATE_PAYER_NEW_CALC

-- CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_CON_TYPE_NEW_CALC definition

create or replace TABLE CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_CON_TYPE_NEW_CALC cluster by (
	PAYERID, PROVIDERID, CRDATEUNIQUE, CONTYPE, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY, SERVICECODE
)(
	PAYERID VARCHAR(50),
	PROVIDERID VARCHAR(50),
	CRDATEUNIQUE DATE,
	CONTYPE VARCHAR(25),
	CONTYPEDESC VARCHAR(100),
	STATUSFLAG VARCHAR(5),
	COSTTYPE VARCHAR(20),
	VISITTYPE VARCHAR(20),
	COUNTY VARCHAR(100),
	SERVICECODE VARCHAR(50),
	CO_TO NUMBER(38,0),
	CO_SP NUMBER(38,2),
	CO_OP NUMBER(38,2),
	CO_FP NUMBER(38,2)
);

-- CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_AGENCY_NEW_CALC definition

create or replace TABLE CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_AGENCY_NEW_CALC cluster by (PAYERID,PROVIDERID, CRDATEUNIQUE,  STATUSFLAG, COSTTYPE, VISITTYPE,COUNTY, SERVICECODE)(
	PAYERID VARCHAR(50),
	PROVIDERID VARCHAR(50),
	CRDATEUNIQUE DATE,
	P_NAME VARCHAR(100),
	STATUSFLAG VARCHAR(5),
	COSTTYPE VARCHAR(20),
	VISITTYPE VARCHAR(20),
	COUNTY VARCHAR(100),
	SERVICECODE VARCHAR(50),
	CON_TO NUMBER(38,0),
	CON_SP NUMBER(38,2),
	CON_OP NUMBER(38,2),
	CON_FP NUMBER(38,2)
);


-- CONFLICTREPORT_SANDBOX.TEST_STATE_CAREGIVER_NEW_CALC definition

create or replace TABLE CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_CAREGIVER_NEW_CALC cluster by (PAYERID,PROVIDERID, CRDATEUNIQUE,SSN,C_NAME,STATUSFLAG,COSTTYPE,VISITTYPE,COUNTY,SERVICECODE)(
	PAYERID VARCHAR(50),
	PROVIDERID VARCHAR(50),
	CRDATEUNIQUE DATE,
	SSN VARCHAR(50),
	C_NAME VARCHAR(100),
	STATUSFLAG VARCHAR(5),
	COSTTYPE VARCHAR(20),
	VISITTYPE VARCHAR(20),
	COUNTY VARCHAR(100),
	SERVICECODE VARCHAR(50),
	CON_TO NUMBER(38,0),
	CON_SP NUMBER(38,2),
	CON_OP NUMBER(38,2),
	CON_FP NUMBER(38,2)
);


-- CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_PATIENT_NEW_CALC definition

create or replace TABLE CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_PATIENT_NEW_CALC cluster by (PAYERID, PROVIDERID, CRDATEUNIQUE, PATIENTID, PNAME, STATUSFLAG, COSTTYPE, VISITTYPE, COUNTY, SERVICECODE)(
	PAYERID VARCHAR(50),
	PROVIDERID VARCHAR(50),
	CRDATEUNIQUE DATE,
	PATIENTID VARCHAR(50),
	PNAME VARCHAR(100),
	STATUSFLAG VARCHAR(5),
	COSTTYPE VARCHAR(20),
	VISITTYPE VARCHAR(20),
	COUNTY VARCHAR(100),
	SERVICECODE VARCHAR(50),
	CON_TO NUMBER(38,0),
	CON_SP NUMBER(38,2),
	CON_OP NUMBER(38,2),
	CON_FP NUMBER(38,2)
);


-- CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_PAYER_NEW_CALC definition

create or replace TABLE CONFLICTREPORT_SANDBOX.PUBLIC.TEST_STATE_PAYER_NEW_CALC cluster by (
PAYERID,PROVIDERID, CRDATEUNIQUE, PNAME, STATUSFLAG, COSTTYPE, VISITTYPE,COUNTY,
	SERVICECODE
)(
	PAYERID VARCHAR(50),
	PROVIDERID VARCHAR(50),
	CRDATEUNIQUE DATE,
	PNAME VARCHAR(100),
	STATUSFLAG VARCHAR(5),
	COSTTYPE VARCHAR(20),
	VISITTYPE VARCHAR(20),
	COUNTY VARCHAR(100),
	SERVICECODE VARCHAR(50),
	CON_TO NUMBER(38,0),
	CON_SP NUMBER(38,2),
	CON_OP NUMBER(38,2),
	CON_FP NUMBER(38,2)
);